//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reminder.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reminder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap gif01 {
            get {
                object obj = ResourceManager.GetObject("gif01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap gif02 {
            get {
                object obj = ResourceManager.GetObject("gif02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap gif03 {
            get {
                object obj = ResourceManager.GetObject("gif03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap gif04 {
            get {
                object obj = ResourceManager.GetObject("gif04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap gif05 {
            get {
                object obj = ResourceManager.GetObject("gif05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap sit_128 {
            get {
                object obj = ResourceManager.GetObject("sit_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap sit_32 {
            get {
                object obj = ResourceManager.GetObject("sit_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap sit_64 {
            get {
                object obj = ResourceManager.GetObject("sit_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap sport_64_01 {
            get {
                object obj = ResourceManager.GetObject("sport_64_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap sport_64_02 {
            get {
                object obj = ResourceManager.GetObject("sport_64_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap sport_64_03 {
            get {
                object obj = ResourceManager.GetObject("sport_64_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 原地踏步的时候，手掌向上朝天花板的方向推出去，手掌收回来的时候大拇指差不多要碰到你的肩膀。通过同时托举水瓶可以加大难度。 的本地化字符串。
        /// </summary>
        internal static string str01 {
            get {
                return ResourceManager.GetString("str01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两手叉腰，左腿向左侧滑动，上身跟着移动，最大跨度后，腿部弯曲下蹲，右腿保持伸直。归位，向右再来一遍 的本地化字符串。
        /// </summary>
        internal static string str02 {
            get {
                return ResourceManager.GetString("str02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两手向左挥动手臂高过你的头顶，换腿的时候手臂向下，然后向右再来一遍。高喊 我爱上班？自己决定哦。 的本地化字符串。
        /// </summary>
        internal static string str03 {
            get {
                return ResourceManager.GetString("str03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 站直或坐直，将右手手背抵在腰上，将左手举过头顶，放在头上；左手慢慢地把头拉向左肩，伸展脖子右侧的肌肉 的本地化字符串。
        /// </summary>
        internal static string str04 {
            get {
                return ResourceManager.GetString("str04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 站直或坐直，努力向下收紧两侧肩胛骨，就像肩胛骨之间有一支铅笔需要抓住一样。这个过程中，要避免耸肩。保持5秒钟，然后放松，重复10次。你应该能感觉到肩膀上斜方肌的拉伸。 的本地化字符串。
        /// </summary>
        internal static string str05 {
            get {
                return ResourceManager.GetString("str05", resourceCulture);
            }
        }
    }
}
